### ISSUE TITLE
Error writing to database no new user on Moodle

### ISSUE THREAD

**Issue by raramuridesign** [frumbert/wp2moodle#11]
@frumbert 
So, the plugin has been working well, thanks

Just recently some users register on WP and then click to goto the classroom, but the plugin is no longer auto logging them in.
We get this message directly after login.

![image](https://user-images.githubusercontent.com/902376/128505583-c0c5997c-0dbd-4385-857a-350ce975467e.png)

Now, we had this last time when users existed, but these users are new, any reason why this would be happening.

Matthew

**Comment by raramuridesign** [comment]
@frumbert The new release does not solve this error.
How do we go about solving this?

**Comment by frumbert** [comment]
Commit https://github.com/frumbert/wp2moodle/commit/16fbcf6bd28e46f88d109670d72a57f52b6feb19 should resolve this. You could replace this one file in the Moodle end, or get the latest release.

**Comment by raramuridesign** [comment]
Solved

1. Since we were looking for a user with a specific email, we of course could not find this user. (legacy user)
2. Turning on debug (developer & display errors) showed us that the username was not being inserted.
3. The username is made up of **namesurname** so finding this and then removing the user fixed this issue.

@frumbert 
Suggestion on improving this.
**Option 1** - Insert email address into username to make it unique.
**Option 2** - combing name & surname, but insert a random number after this - making it unique.

We hope that option 1 will be added or at least an option in the settings to choose between option 1 & 2.

It might also be good, to update username field as new users login, so the username field is updated overtime.

Thanks
M.
