### ISSUE TITLE
suspended users allowed to login

### ISSUE THREAD

**Issue by raramuridesign** [frumbert/wp2moodle#12]
Hi @frumbert 
We have picked up the following which we would like to know if this can be addressed.

If a user is suspended on Moodle's side, the user can still login using WP2Moodle.

Would it be possible to build a check to prevent the user from logging in if the user has been suspended on Moodle's side.
It would also be great, if we could redirect the user to a page informing them why this is potentially an issue.

Please would you let me know if this is a possibility to add. 

Currently the plugin does not respect this.

Looking forward to some feedback
M.

**Comment by frumbert** [comment]
This change adds the url to redirect to (defaults to the moodle login page with the default 'invalid login' message you normally get). Detects if a user has been marked as suspended or deleted.

**Comment by raramuridesign** [comment]
@frumbert Many thanks. I have already integrated this into our workflow and it works as expected.
Having the bonus logout and redirect links (for suspended) works well.

Cheers
M.
