### ISSUE TITLE
Compatible with WC payment gateways and Product Bundles?

### ISSUE THREAD

**Issue by vsalgadinho** [frumbert/wp2moodle#13]
Hi Frumbert,

I am new to the field of web development, but I am trying to integrate WordPress/WooCommerce with Moodle. I am looking for a plugin that provides both single sign-on and enrollment from WooCommerce to Moodle. From my understanding, your plugin does provide these functionalities, however, the sing-on/enrollment in Moodle courses is not automatic, correct? I mean, after purchasing the course from WooCommerce users need to click on a link (that can be sent to them by email, for example), in order to sign on and enroll in that particular course(s) they purchased. If that's the case, can you please confirm if your plugin is fully compatible with all Woocomerce payment gateways plugins (Stripe, PayPal, credit card, amazon pay) and with the WooCommerce Product Bundles plugin as well?

Thanks!

**Comment by raramuridesign** [comment]
@vsalgadinho 
Just so you understand how it works.

The plugin allows wordpress users to auto login to moodle. They can only access courses they have been enrolled into manually or automatically.
The payment gateways you mentioned only integrate with WP/Woocomerce.  So this process has nothing to do with the access to moodle.

**However**
You should be aiming for a process where the user pays for a course and then is able to see a link generating their access to the course they ordered. This link can only be added within WP.  Examples of this are here
https://github.com/frumbert/wp2moodle

_An example_

`[wp2moodle group='eng14_a,math14_b,hist13_c']Math, English & History[/wp2moodle]`

Sending this link via email will not work, but I am sure with some coding you can achieve these links purely on a dashboard for the user or something like this.

Hope this helps.
M.

**Comment by vsalgadinho** [comment]
Hi @raramuridesign,

Thanks for clarifying this for me. Well, it seems a bit complicated for my current level of knowledge. Unfortunately, I do not have coding skills so maybe this option is not the right choice for me at the moment, but thanks anyway.

Best,
Vânia

**Comment by raramuridesign** [comment]
Of course @vsalgadinho You should try it, it is very powerful once you have this integrated.
Close this when you are done. Thanks.
