### ISSUE TITLE
Plugin creating duplicated user account on Moodle

### ISSUE THREAD

**Issue by polamsky** [frumbert/wp2moodle#4]
I've been using this plugin for a couple of years now and just started having this issue. 

I run Wordpress on 2 separate sites that link to the same Moodle. Both Wordpress sites run exactly the same configuration and sit on the same server, but they have different URLs.

Some users have accounts on both websites (with same username and email) and up until a few months ago, the plugin seemed to work flawlessly matching their details on Moodle and logging them in. But recently, the plugin has started duplicating the account on Moodle for some of these users (with a random username) and if I delete the new Moodle account, the user gets an 'Error Writing to Database' error when trying to login.

Any ideas on why this started happening out the blue?

**Comment by raramuridesign** [comment]
@frumbert 
is this error related to the same issue I am having?

**Comment by frumbert** [comment]
Without seeing the details of the error I can’t really tell what the problem is.

To get the error to show you need to enabled developer debugging on the Moodle site. To do this, log on to Moodle as the admin, then click on Site Administration > Development > Debugging and enable debug messages (set it to DEVELOPER) and check the Display Debug Messages box then save.

Retry the same link and it should expose some programming information which might point me in the right direction for further assistance.

Cheers
Tim

**Comment by raramuridesign** [comment]
@frumbert I have commented on the issue we raised. 
@polamsky you may want to read the info on this
https://github.com/frumbert/wp2moodle/issues/5

**Comment by polamsky** [comment]
@frumbert @raramuridesign That's exactly the same problem I'm having, the system is trying to duplicate a user that already exists, but doesn't have an idnumber.

But the interesting thing is, on one of the instances of Wordpress that I am running, I don't have this issue, it lets the very same users in. The other instance of Wordpress gets an error (image below) when these users try to log in. Both sites were created at the same time 12 months ago and the integration of both with Moodle at the time were working seamlessly.

I'm not sure if the idnumber is a new thing, but my understanding till now was that it would try to match the email address on Moodle and not anything else, but I guess I'm incorrect.

![Screen Shot 2021-03-14 at 2 06 50 pm](https://user-images.githubusercontent.com/55284045/111057052-09f44700-84d0-11eb-8dd0-a998a4706768.png)

**Comment by frumbert** [comment]
@polamsky See if my latest checkin helps. You can now specify the field to try matching users on (plus some bugfixes)

**Comment by polamsky** [comment]
@frumbert Love your work! It works like a dream now, thank you so much.
