### ISSUE TITLE
Error - Invalid User

### ISSUE THREAD

**Issue by moleary1977** [frumbert/wp2moodle#8]
Hi, I have set this up as per instructions and when first clicking the access link on Wordpress I get the error "Invalid User" but if I go back and try again I can get access to moodle.

Debug info: SELECT id FROM {user} WHERE id IS NULL AND deleted = ?
[array (
0 => 0,
)]
Error code: invaliduser
Stack trace:

    line 1562 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
    line 1538 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
    line 6395 of /lib/accesslib.php: call to moodle_database->get_record()
    line 129 of /lib/classes/event/user_created.php: call to context_user::instance()
    line 150 of /auth/wp2moodle/login.php: call to core\event\user_created::create_from_userid()

OpenSSL is installed on Wordpress and I am using the latest version of Wordpress and Moodle 3.8.

The shortcode I use is as follows: [wp2moodle course='Far8' target='_blank' authtext='Please log on']Access Farcura E-Learning[/wp2moodle]

Far8 is the course id number.

The auth key is the same on Moodle and Wordpress.

Have you seen this error before? 

Edwiser bridge is installed on Moodle as another site is using that for access to a different course.

**Comment by linhatech** [comment]
the same is happening to me

**Comment by rajibb** [comment]
I am facing the same issue, it is throwing the error message for the first time and subsequent calls are working fine.

**Comment by TharinduX** [comment]
Facing the same issue here.

**Comment by TharinduX** [comment]
I found the solution, in the login.php line 150 change

`\core\event\user_created::create_from_userid($user->id)->trigger();` 

to 

`\core\event\user_created::create_from_userid($updateuser->id)->trigger();` 

And it will work.

**Comment by rajibb** [comment]
Can confirm this fixed it for me. Thanks

**Comment by raramuridesign** [comment]
@frumbert Should this not be tested and added to the code if this works?
See @TharinduX note above.

**Comment by frumbert** [comment]
Good catch. Patched.

**Comment by raramuridesign** [comment]
@frumbert Thanks for updating the core ;-)
